spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/boxtobox
spring.datasource.username=berdasonbadel
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true